language: node_js
node_js:
  - 8.6.0
  
script:
  - mkdir docs/manual/asset
  - npm test
  - npm run docs

cache:
  directories:
  - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs
  on:
    branch: master